export const SET_ALL_CONNECTIONS = "SET_ALL_CONNECTIONS";
export const SET_ALL_CONNECTION_REQUEST = "SET_ALL_CONNECTION_REQUEST";
export const SET_ALL_USERS = "SET_ALL_USERS";
export const SET_ALL_PENDING_USERS = "SET_ALL_PENDING_USERS";
